# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86f81d27dbe4dbbe0e585bcad9296f79d9621f4da9bc48bb5bc98ee4e94de8118b6e8efe478a72cdc11f19fed03d48e77dc51ca7283e4df78d68380fcbead8fb

test:
  secret_key_base: 3d1635056260b92c490b60de2804d0e0e0f5833ab47103dd9da8db5f0febd623e7fe2c54a81538662abaab14fb28fbff137188a472ec6898d3ba2a56582c99ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
